updated installation mode. Code prepared for merging into master

diff --git a/environment/resources/20_gitea/setup-job.yaml b/environment/resources/20_gitea/setup-job.yaml
--- a/environment/resources/20_gitea/setup-job.yaml
+++ b/environment/resources/20_gitea/setup-job.yaml
@@ -30,7 +30,7 @@ spec:
           cd repository
 
           echo "-- Cloning demo repository --"
-          git clone -b feature/cicd-pipeline https://github.com/clbartolome/openshift-devops.git  
+          git clone -b master https://github.com/clbartolome/openshift-devops.git  
           echo "------------------------------"   
 
           echo "-- Creating gitea user"
@@ -140,6 +140,18 @@ spec:
               echo "Error protecting master branch, error code: $RESPONSE"
               exit 1
           fi
+
+          echo "-- Create PR Hook in applications collection repository --"
+          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
+            -u gitea:openshift \
+            -d '{"active": true,"branch_filter": "master","config": {"content_type": "json","url": "http://el-ci-cd.ci-cd-workspace.svc.cluster.local:8080"},"events": ["push"],"type": "gitea"}' \
+            -H "Content-Type: application/json" \
+            http://$GITEA_HOSTNAME/api/v1/repos/gitea/lol-champions-app/hooks)
+
+          if [ "$RESPONSE" != "201" ]; then
+              echo "Error creating webhook, error code: $RESPONSE"
+              exit 1
+          fi 
           
         imagePullPolicy: Always
       restartPolicy: Never
